---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ingress
  namespace: bomc-app
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    #ingress.kubernetes.io/ssl-redirect: "false"
    # Avoid the Google Compute Engine controller from processing this Ingress.
    ingress.kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
   - host: bomc.ingress.org
     http:
      paths:
      - path: /${artifactId}
        backend:
          serviceName: ${artifactId}-svc
          servicePort: 80