---
apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-svc
  namespace: bomc-app
spec:
  selector:
    app: ${artifactId}
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 8080
