apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomize does not have edit set label command to add a label, but one can always edit kustomization.yaml directly:
commonLabels:
  env: prod
  
resources:
- ./base/010-dc.yaml
- ./base/020-svc.yaml
- ./base/030-role.yaml
- ./base/040-rolebinding.yaml
- ./base/050-route.yaml

configMapGenerator:
- files:
  - ./overlays/prod/application.properties
  - ./overlays/prod/application-prod.properties
  name: ping-cm

#- ./overlays/prod/030-patch-env-dc.yaml
patchesStrategicMerge:
- ./overlays/prod/030-patch-env-dc.yaml
- ./overlays/prod/020-patch-memorylimit_dc.yaml
- ./overlays/prod/010-patch-healthcheck_dc.yaml
#- ./overlays/prod/020-patch-memorylimit_dc.yaml
#- /overlays/prod/010-patch-healthcheck_dc.yaml
namePrefix: prod-
