---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: bomc-app
  labels:
    name: kafka-manager
    app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      name: kafka-manager
      labels:
        app: kafka-manager
        name: kafka-manager
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: kafka-manager
        image: sheepkiller/kafka-manager@sha256:615f3b99d38aba2d5fdb3fb750a5990ba9260c8fb3fd29c7e776e8c150518b78
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zookeeper-service:2181"
---
