apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ping
spec:
  project: ping
  source:
    repoURL: https://github.com/bomc/hack/bomc-kustomize-argocd-apps-ping
    targetRevision: master
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
