apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc
spec:
  project: poc
  source:
    repoURL: 
    targetRevision: master
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true