---
apiVersion: v1
kind: Service
metadata:
  name: bomc-hrm-service
  namespace: bomc-app
  labels:
    app: bomc-hrm
    name: bomc-hrm
spec:
  type: NodePort
  selector:
    app: bomc-hrm
    name: bomc-hrm
  ports:
  - protocol: TCP
    name: http
    port: 8080
    nodePort: 30081
    #port: 80
    #targetPort: 8080
---
