apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bomc-app
  name: bomc-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "configmaps"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: bomc-role-binding
  namespace: bomc-app
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bomc-app
roleRef:
  kind: Role
  name: bomc-role
  apiGroup: rbac.authorization.k8s.io