---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bomc-hrm
  namespace: bomc-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bomc-hrm
        # version: v1.0.0
      # Monitoring: Adjust prometheus configuration
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/bomc-hrm/actuator/prometheus"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: bomc-hrm
        image: bomc/bomc-hrm:v1.0.0
        imagePullPolicy: IfNotPresent
#         resources:
#           limits:
#             cpu: "250m"
#             memory: "750Mi"
#           requests:
#             cpu: "200m"
#             memory: "700Mi"
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 15
          httpGet:
            path: /bomc-hrm/actuator/health
            port: 8080
        readinessProbe:
          initialDelaySeconds: 15
#          periodSeconds: 5
          httpGet:
            path: /bomc-hrm/actuator/info
            port: 8080
#      restartPolicy: Always
---