---
apiVersion: v1
kind: Service
metadata:
  name: bomc-hrm-service
  namespace: bomc-app
  labels:
    app: bomc-hrm
spec:
  selector:
    app: bomc-hrm
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 8080
---