---
# Allow HTTP traffic on Port 80, for all hosts.
# The gateway now allows access in port 80 but it has no concept where to route the requests.
#
# That is achieved using Virtual Services.
#
# 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  # Is by default in istio-system namespace.
  namespace: istio-system
  name: istio-bomc-app-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # should not be used in production
---
