---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-wf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-wf
    spec:
      containers:
      - name: kafka-wf
        image: bomc/kafka-wf:v1.0.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /kafka-poc/bomc-app/health/version
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 15