---
apiVersion: v1
kind: Service
metadata:
  name: bomc-controller-svc
  namespace: bomc-app
spec:
  selector:
    app: bomc-controller
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 8080
