apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ping
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
