apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./../../base

#patchesStrategicMerge:
#- 010-patch-healthcheck_dc.yaml

#configMapGenerator:
#- files:
#  - ./prod/application.properties
#  - ./prod/application-prod.properties
#  name: ping-cm

# kustomize does not have edit set label command to add a label, 
# but one can always edit kustomization.yaml directly:
#commonLabels:
#  env: prod
