apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc
spec:
  project: poc
  source:
    repoUrl: 
    targetRevision: master
    path: "overlays/prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: poc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
