apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bomc-kustomize-ping
  name: bomc-role-kustomize-poc
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
