apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres
  labels:
    app: ping
spec:
  replicas: 1
  #selector:
    #app: postgres
    #deploymentconfig: postgres
  template:
    metadata:
      labels:
        app: ping
        deploymentconfig: postgres
    spec:
      containers:
      - name: postgres
        image: 172.30.1.1:5000/openshift/postgresql@sha256:2727b9b84cc03271c2c3b3cd954de1c5a4f025200b2eaff6bb7d1a7401930d2a
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        # Define the environment variable
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value to assign to POSTGRESQL_DATABASE
              name: ping-cm
              # Specify the key associated with the value
              key: POSTGRESQL_DATABASE
        # Define the environment variable
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_USER
              name: bomc-ping-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_USER
        # Define the environment variable
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_PASSWORD
              name: bomc-ping-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_PASSWORD
        volumeMounts:
        - name: "postgres-data"
          mountPath: "/var/lib/pgsql/data"
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities: {}
          privileged: false
      volumes:
      - name: "postgres-data"
        emptyDir:
          medium: ''
          
