apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    app: postgres
    deploymentconfig: postgres
  template:
    metadata:
      labels:
        app: postgres
        deploymentconfig: postgres
    spec:
      containers:
      - name: postgres
        image: 172.30.1.1:5000/bomc/postgres:9.6.17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        # Define the environment variable
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value to assign to POSTGRESQL_DATABASE
              name: ping-cm
              # Specify the key associated with the value
              key: POSTGRESQL_DATABASE
        # Define the environment variable
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_USER
              name: bomc-ping-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_USER
        # Define the environment variable
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_PASSWORD
              name: bomc-ping-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_PASSWORD