apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping
  name: ping
spec:
  replicas: 1
  #selector:
  #  app: ping
  #  deploymentconfig: ping
  template:
    metadata:
      labels:
        app: ping
        deploymentconfig: ping
    spec:
      containers:
        - name: ping
          image: 172.30.1.1:5000/bomc/ping:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # Set 'envFrom' to references 'ping-cm' file, see 030-postgres-cm-base.
          envFrom:
          - configMapRef:
              name: ping-cm
          env:
          # Define the environment variable
          - name: POSTGRES_DB_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value to assign to POSTGRES_DB_SERVICE_NAME
                name: ping-cm
                # Specify the key associated with the value
                key: POSTGRES_DB_SERVICE_NAME
          - name: POSTGRESQL_DATABASE
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value to assign to POSTGRESQL_DATABASE
                name: ping-cm
                # Specify the key associated with the value
                key: POSTGRESQL_DATABASE
          # Define the environment variable
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                # The secrets containing the value to assign to POSTGRES_DB_USER
                name: bomc-ping-secret
                # Specify the key associated with the value
                key: POSTGRES_DB_SECRETS_USER
          # Define the environment variable
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                # The secrets containing the value to assign to POSTGRES_DB_PASSWORD
                name: bomc-ping-secret
                # Specify the key associated with the value
                key: POSTGRES_DB_SECRETS_PASSWORD
      initContainers:
        - command:
            - sh
            - '-c'
            - >-
              until pg_isready -h postgres-service -p 5432 -U adapter; do echo wait for database; sleep 2; done;
          image: 172.30.1.1:5000/openshift/postgresql@sha256:2727b9b84cc03271c2c3b3cd954de1c5a4f025200b2eaff6bb7d1a7401930d2a
          imagePullPolicy: IfNotPresent
          name: postgres_ready_check