apiVersion: v1
kind: Service
metadata:
  name: ping-service
  labels:
    app: ping
spec:
  selector:
    app: ping
    deploymentconfig: ping
  ports:
  - protocol: TCP
    name: 8080-tcp
    port: 8080
    targetPort: 8080