apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add labels to all objects created by this kustomize manifest.
commonLabels:
  app: ping

resources:
#- 010-namespace-base.yaml
- 020-pre-sync-job-base.yaml
- 021-role-pre-sync-job-base.yaml
- 022-rolebinding-pre-sync-job-base.yaml
- 030-postgres-cm-base.yaml
- 040-postgres-dc-base.yaml
- 050-postgres-svc-base.yaml
- 060-postgres-secret-base.yaml
- 070-ping-dc-base.yaml
- 080-ping-svc-base.yaml

