apiVersion: v1
kind: Route
metadata:
  labels:
    app: ping
  name: ping-route
spec:
  host: ping-route.192.168.99.101.nip.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: ping-service
    weight: 100
  wildcardPolicy: None