apiVersion: v1
kind: Route
metadata:
  labels:
    app: ping
  name: ping
spec:
  host: ping-pong.127.0.0.1.nip.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: ping-service
    weight: 100
  wildcardPolicy: None