apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kustomize-poc
  name: bomc-role-kustomize-poc
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: bomc-role-binding-kustomize-poc
  namespace: kustomize-poc
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kustomize-poc
roleRef:
  kind: Role
  name: bomc-role-kustomize-poc
  apiGroup: rbac.authorization.k8s.io