---
apiVersion: v1
kind: Route
metadata:
  namespace: bomc-kustomize-ping
  labels:
    app: ping
  name: ping-route
spec:
  port:
    targetPort: 8080-tcp
  path: "/"
  to:
    kind: Service
    name: ping-service
    weight: 100
  wildcardPolicy: None

