apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: oc-client
        image: 172.30.1.1:5000/bomc/appuio-oc:v3.11
        command: ["oc", "create", "configmap", "special-config", "--from-literal=special.how=very"]
      restartPolicy: Never
  backoffLimit: 0