apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: 172.30.1.1:5000/openshift/postgresql@sha256:617c75aab798753ee5e0323d60069757b17a2255abd9de44ca342e4a8bb68b15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        # Define the environment variable
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value to assign to POSTGRESQL_DATABASE
              name: ping-cm
              # Specify the key associated with the value
              key: POSTGRES_DB_NAME
        # Define the environment variable
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_USER
              name: bomc-ping-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_USER
        # Define the environment variable
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_PASSWORD
              name: bomc-ping-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_PASSWORD
