apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: 5432-tcp
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
    deploymentconfig: postgres
