---
apiVersion: v1
kind: ReplicationController
metadata:
  name: registrator-wf
  namespace: bomc-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registrator-wf
    spec:
      containers:
      - name: registrator-wf
        image: bomc/registrator-wf:v1.0.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /registrator-app/api/health/version
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 15