---
apiVersion: v1
kind: Service
metadata:
  name: registrator-wf
  namespace: bomc-app
  labels:
    app: registrator-wf
spec:
  type: NodePort
  selector:
    app: registrator-wf
  ports:
  - protocol: TCP
    port: 8080
    name: http
    #targetPort: 8080
    # bomc Use this port for Browser access
    nodePort: 30082