---
apiVersion: v1
kind: Service
metadata:
  name: bomc-invoice-service
  namespace: bomc-app
  labels:
    app: bomc-invoice
spec:
  type: NodePort
  selector:
    app: bomc-invoice
  ports:
  - protocol: TCP
    port: 8080
    name: http
    # bomc Use this port for Browser access
    nodePort: 30082
    # To access the version endpoint, bomc-invoice is the context-root, given in the jboss-web.xml
    # curl -v 192.168.99.100:30082/bomc-invoice/rest/version/current-version -H "accept: application/vnd.version-v1+json"
---