---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: bomc-app
  labels:
    app: keycloak
    name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
      #targetPort: 8080
      #port: 80
  selector:
    app: keycloak
    name: keycloak
---
