apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: ping
  name: ping
spec:
  template:
    spec:
      containers:
      - name: ping
        env:
        - name: spring.profiles.active
          value: prod