# The VirtualService instructs the Ingress Gateway how to route the requests that were allowed into the cluster.
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-bomc-app-virtualservice
  namespace: bomc-app
spec:
  hosts:
  - "*"
  gateways:
  # This VirtualService applies to requests coming through the istio-bomc-app-gateway.
  - istio-bomc-app-gateway.istio-system.svc.cluster.local
  http:
  - route:
    - destination:
        host: bomc-invoice
        port:
          number: 80
        # subset: v1
---