apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ping
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: ping
  source:
    repoUrl: 
    targetRevision: master
    path: "overlays/prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: ping
  syncPolicy:
    automated:
      prune: false
      selfHeal: true