apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bomc-kustomize-argocd-ping-apps
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  
  # Source of the application manifests
  source:
    repoURL: https://github.com/bomc/hack
    targetRevision: master
    path: "bomc-kustomize-argocd-ping/overlays/prod"
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: bomc-kustomize-ping
  
  # Sync policy
  syncPolicy:
    automated:
      # Specifies if resources should be pruned during auto-syncing ( false by default ).
      prune: false
      # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change.
      selfHeal: true
