---
apiVersion: v1
kind: Service
metadata:
  name: bomc-hrm-service
  namespace: bomc-app
  labels:
    app: bomc-hrm
spec:
  type: NodePort
  selector:
    app: bomc-hrm
  ports:
  - protocol: TCP
    port: 8080
    name: http
    # bomc Use this port for Browser access
    nodePort: 30082
    # To access the version endpoint.
    # curl -v 192.168.99.100:30082/bomc-order/rest/version/current-version -H "accept: application/vnd.version-v1+json"
---