---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bomc-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: postgres
        image: bomc/postgres:v9.6.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        # Define the environment variable
        - name: POSTGRES_DB_NAME
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value to assign to POSTGRES_DB_NAME
              name: hrm
              # Specify the key associated with the value
              key: POSTGRES_DB_NAME
        # Define the environment variable
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_USER
              name: bomc-hrm-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_USER
        # Define the environment variable
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              # The secrets containing the value to assign to POSTGRES_DB_PASSWORD
              name: bomc-hrm-secret
              # Specify the key associated with the value
              key: POSTGRES_DB_SECRETS_PASSWORD
---
