---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: bomc-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: postgres
        image: bomc/postgres:v9.6.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: bomcdb
        - name: POSTGRES_USER
          value: bomc
        - name: POSTGRES_PASSWORD
          value: bomc

---