apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ping
spec:
  template:
    spec:
      containers:
      - name: ping
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi