apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ping
spec:
  selector:
    app: ping
    deploymentconfig: ping
  template:
    spec:
      containers:
      - name: ping
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          httpGet:
            path: /
            port: 8080
